[build]
  command = "yarn build"
  publish = "dist"
  environment = { NODE_VERSION = "14" }

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = '''
      default-src 'self' https://fonts.gstatic.com; 
      script-src 'self' 'unsafe-inline' https://storage.googleapis.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      object-src 'none'
    '''
    Feature-Policy = "fullscreen 'self'"
    Referrer-Policy = "same-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
